# API Keys and Secrets
# Values are loaded from environment variables
twitter:
  consumer_key: ${TWITTER_CONSUMER_KEY}
  consumer_secret: ${TWITTER_CONSUMER_SECRET}
  access_token: ${TWITTER_ACCESS_TOKEN}
  access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}

openai:
  api_key: ${OPENAI_API_KEY}

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region_name: ${AWS_REGION_NAME}
  s3_bucket: ${AWS_S3_BUCKET}

# Application Settings
app:
  debug: ${APP_DEBUG}
  host: ${APP_HOST}
  port: ${APP_PORT}

# Paths
paths:
  templates: "data/imgflip_templates.json"
  sample_memes: "data/sample_memes/"
  static: "webapp/static/"

# AI Settings
ai:
  caption_model: ${AI_CAPTION_MODEL}
  image_model: ${AI_IMAGE_MODEL}
  max_tokens: ${AI_MAX_TOKENS}
  temperature: ${AI_TEMPERATURE} 